id: P006882
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:28:30.663167
source_metadata:
  id: bdr:W27314
  title: བོད་ལྗོངས་ཀྱི་ལོ་རྒྱུས་གོ་བབ་དཔྱད་ཞིབ
  author: ''
  volumes:
    6a38f5374d6249bdb0b8976662521587:
      image_group_id: I4313
      title: ''
      volume_number: 1
      total_pages: 764
      base_file: v001.txt
    acbb6f3e39cf4d50ae699b12e80dfb73:
      image_group_id: I4314
      title: ''
      volume_number: 2
      total_pages: 793
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
